### PR TITLE
Refactor generate functions slightly to use structs for default returns (plus json output).

### PR DESCRIPTION
**Pull request by IngCr3at1on**
#### What does this change do?

- Refactor generate functions slightly to use structs for default returns.
- Adds JSON support.
- Includes go.mod files for module build support (allows building this package
outside of gopath).

These changes are not backwards compatible with previous implementations.

#### How was this change implemented?

Changes generate functions to return struct pointers, string functions exist on these structs; this will both make it easier to add values while making the API easier to maintain in the future.

#### How is this change tested?

Run `build.sh` to compile the binaries and tested them as normal (if using Go 1.11 (above, or vgo) this can be done from outside of $GOPATH.

#### What issues are associated with this change?

#3

### CODE REVIEW

**Comment by david-kroell** [comment]
How much effort would it take to add another output format with the current implementation? 
Like CSV for example

**Comment by BenOvermyer** [comment]
@IngCr3at1on This is impressive work, and I love that you tried to protect the original API.

However, I didn't give you all of the information that would have been pertinent to this particular kind of change. Specifically, I had already intended to rip out all "display" logic from the existing places, and put them in different functions.

We don't need to maintain API compatibility, despite the Go directive to do so, because there are no external downstream users of this package yet.

I hate asking for rework, but if you could refactor this PR to drop the Go module pattern and eliminate the original API, that would be ideal for the current use case.

@david-kroell while CSV output is intended as a later feature, it's out of scope for this particular issue.

**Comment by david-kroell** [comment]
@BenOvermyer yes of course, I also don't want it to be implemented in this pull.
I just wanted to know how much effort it is with this pattern already created.

I'm asking because I thought about implementing a CSV export feature (or other encodings).

**Comment by BenOvermyer** [comment]
@david-kroell This PR will determine the nature of a CSV feature's implementation, but yeah, that'd be fair game after this gets merged.

**Comment by IngCr3at1on** [comment]
@BenOvermyer that's no problem at all (part of why I asked in the actual comments); it's an easy change I just did it the way I did to avoid breaking anything at first. I'm happy to change this for you; as for outputting CSV data that is actually quite easy once you're using a structs for your data.

**Comment by IngCr3at1on** [comment]
@BenOvermyer please take another look (the branch name is no longer valid but I didn't want to create a new PR lol)

**Pull request merged**
